"use client";

import { useLanguage } from "../providers/LanguageProvider";

export default function Hero() {
  const { t } = useLanguage();

  return (
    <section
      id="home"
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
        padding: "6rem 1.5rem 4rem",
        position: "relative",
        overflow: "hidden",
        background: "#0f172a",
      }}
    >
      {/* Background SVG — generated by Media Agent */}
      <img
        src="/oitt-hero-banner-digital-agency-abstract-technology.svg"
        alt=""
        aria-hidden="true"
        style={{
          position: "absolute",
          inset: 0,
          width: "100%",
          height: "100%",
          objectFit: "cover",
          opacity: 0.6,
          pointerEvents: "none",
        }}
      />

      {/* Dark overlay for text readability */}
      <div
        style={{
          position: "absolute",
          inset: 0,
          background:
            "radial-gradient(ellipse at center, rgba(15,23,42,0.3) 0%, rgba(15,23,42,0.7) 100%)",
          pointerEvents: "none",
        }}
      />

      <div style={{ position: "relative", zIndex: 1, maxWidth: 720 }}>
        <div className="hero-animate" style={{ animationDelay: "0.1s" }}>
          <h1
            style={{
              fontSize: "clamp(2.5rem, 6vw, 4.5rem)",
              fontWeight: 800,
              lineHeight: 1.1,
              marginBottom: "1.5rem",
              letterSpacing: "-0.03em",
              color: "#fff",
            }}
          >
            {t.hero.title}{" "}
            <span
              style={{
                background: "linear-gradient(135deg, #818cf8, #22d3ee)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}
            >
              {t.hero.highlight}
            </span>
          </h1>
        </div>

        <div className="hero-animate" style={{ animationDelay: "0.3s" }}>
          <p
            style={{
              fontSize: "clamp(1.05rem, 2vw, 1.25rem)",
              color: "#cbd5e1",
              lineHeight: 1.7,
              maxWidth: 560,
              margin: "0 auto 2.5rem",
            }}
          >
            {t.hero.subtitle}
          </p>
        </div>

        <div
          className="hero-animate"
          style={{
            animationDelay: "0.5s",
            display: "flex",
            gap: "1rem",
            justifyContent: "center",
            flexWrap: "wrap",
          }}
        >
          <a href="#contact" className="btn-primary">
            {t.hero.cta} &rarr;
          </a>
          <a href="#portfolio" className="btn-outline">
            {t.hero.secondary}
          </a>
        </div>
      </div>
    </section>
  );
}
