"use client";

import { useLanguage } from "../providers/LanguageProvider";

const PORTFOLIO_IMAGES = [
  "/portfolio-fashion-store-ecommerce-elegant-shopping.svg",
  "/portfolio-management-app-dashboard-analytics-data.svg",
  "/portfolio-law-firm-professional-corporate-trust.svg",
  "/portfolio-booking-platform-saas-reservation-modern.svg",
  "/portfolio-news-portal-media-content-publishing.svg",
  "/portfolio-startup-landing-innovation-tech-growth.svg",
];

export default function Portfolio() {
  const { t } = useLanguage();

  return (
    <section id="portfolio" className="section">
      <div className="fade-in">
        <h2 className="section-title">{t.portfolio.title}</h2>
        <p className="section-subtitle">{t.portfolio.subtitle}</p>
      </div>

      <div className="grid-3">
        {t.portfolio.items.map((item, i) => (
          <div
            key={i}
            className="portfolio-item fade-in"
            style={{ transitionDelay: `${i * 0.1}s` }}
          >
            {/* Portfolio image — generated by Media Agent */}
            <img
              src={PORTFOLIO_IMAGES[i]}
              alt={item.title}
              style={{
                position: "absolute",
                inset: 0,
                width: "100%",
                height: "100%",
                objectFit: "cover",
              }}
            />

            {/* Always-visible label at bottom */}
            <div
              style={{
                position: "absolute",
                bottom: 0,
                left: 0,
                right: 0,
                padding: "1.25rem",
                background: "linear-gradient(to top, rgba(0,0,0,0.75) 0%, transparent 100%)",
                display: "flex",
                alignItems: "flex-end",
                justifyContent: "space-between",
              }}
            >
              <h3
                style={{
                  color: "#fff",
                  fontSize: "1.05rem",
                  fontWeight: 700,
                }}
              >
                {item.title}
              </h3>
              <span
                style={{
                  padding: "0.2rem 0.65rem",
                  borderRadius: "9999px",
                  background: item.color,
                  color: "#fff",
                  fontSize: "0.7rem",
                  fontWeight: 600,
                  whiteSpace: "nowrap",
                }}
              >
                {item.category}
              </span>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
